name = "huynhtu-download-proxy"
main = "worker-proxy.js"
compatibility_date = "2024-01-01"
account_id = "99b87c095b69dbecf541c71e74fb4b8d"

[[routes]]
pattern = "api.huynhtu.com/*"
zone_name = "huynhtu.com"

[[kv_namespaces]]
binding = "LINKS"
id = "eca943d1df30409d853bed5251a060ff"

[[d1_databases]]
binding = "DB"
database_name = "huynhtu-d1"
database_id = "f1623898-8b89-4c44-85ff-ee45db4d14d0"
